### ISSUE TITLE
Wrong Cuttlefish-format - 50-overrideConfig.conf.erb

### ISSUE THREAD

**Issue by kinjelom** [pivotal-cf/cf-rabbitmq-release#442]
This config causes wrong `50-overrideConfig.conf` config format:
```
  instance_groups:
  - name: rmq
    jobs:
    - name: rabbitmq-server
      properties:
        rabbitmq-server:
           override_config:
             prometheus.return_per_object_metrics: 'true'
```
fix: https://github.com/pivotal-cf/cf-rabbitmq-release/pull/441

**Comment by mkuratczyk** [comment]
Hi. This is not a bug but a design choice. This field is meant to be used with YAML multi-line value like this:
```
  instance_groups:
  - name: rmq
    jobs:
    - name: rabbitmq-server
      properties:
        rabbitmq-server:
           override_config: |
             prometheus.return_per_object_metrics = true
             other_property = foo
```

As a side note, you don't need to set this property at all in the recent versions of RabbitMQ. There is now a dedicated endpoint which always returns per-object metrics, even if this value is `false`. Just can just scrape `/metrics/per-object`.
