### ISSUE TITLE
Missing Link Path Deploying release on Openstack

### ISSUE THREAD

**Issue by StBurcher** [pivotal-cf/cf-rabbitmq-release#50]
Hi,

I'm facing the following problem deploying rabbiitmq 224 on openstack.
```
D, [2017-02-13 12:15:56 #29852] [task:443] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"fa0bc75b-d46f-4192-a41d-74ede69af2a5","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'cf-rabbitmq' against Director '87c25ba6-be78-4c13-8c7a-3ca9017594c7': #<Bosh::Director::JobMissingLink: Link path was not provided for required link 'rabbitmq-broker' in instance group 'rmq-broker'>","created_at":1486988156}
E, [2017-02-13 12:15:56 #29852] [task:443] ERROR -- DirectorJobRunner: Link path was not provided for required link 'rabbitmq-broker' in instance group 'rmq-broker'
```

Here is my stub.
```
meta:
  stemcell:
    version: latest
  compilation_az: us-east-1a
  az1: us-east-1a
  az2: us-east-1b

director_uuid: 87c25ba6-be78-4c13-8c7a-3ca9017594c7
name: cf-rabbitmq

releases:
- name: cf-rabbitmq
  version: latest

jobs:
- name: rmq_z1
  instances: 1
  networks:
  - name: rabbitmq_z1
    static_ips:
    - 10.0.0.210

- name: rmq-broker
  instances: 1
  networks:
  - name: rabbitmq_z1
    static_ips:
    - 10.0.0.212

- name: haproxy_z1
  instances: 1
  networks:
  - name: rabbitmq_z1
    static_ips:
    - 10.0.0.213

- name: broker-registrar
  properties:
    broker:
      name: p-rabbitmq

properties:
  # for broker and route registrars
  cf:
    domain: de.cloudlab.com
    admin_password: password 
    admin_username: admin
    api_url: "http://api.de.cloudlab.com"
    nats:
      host: "10.0.0.127"
      port: "4222"
      password: password
      username: nats-user
  rabbitmq-server:
    administrators:
      broker:
        username: username
        password: password
    static_ips:
    - 10.0.0.210
    - 10.0.0.211
    ssl:
      cert: |
        -----BEGIN CERTIFICATE-----
        your certificate
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        your key
        -----END RSA PRIVATE KEY-----
      cacert: |
        -----BEGIN CERTIFICATE-----
        certificate for your CA
        -----END CERTIFICATE-----
  rabbitmq-haproxy:
    stats:
      username: username
      password: password
  rabbitmq-broker:
    ip: 10.0.0.212
    cc_endpoint: http://api.de.cloudlab.com
    service:
      username: "p1-rabbit"
      password: "password"
    logging:
      level: debug
      print_stack_traces: false
    rabbitmq:
      management_domain: pivotal-rabbitmq.de.cloudlab.com
      management_ip: 10.0.0.213
      ssl: false
      hosts:
        - 10.0.0.210

networks:
- name: rabbitmq_z1
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    reserved:
    - 10.0.0.1 - 10.0.0.209
    static:
    - 10.0.0.210 - 10.0.0.220
    dns:
    - 139.25.25.243
    cloud_properties:
      subnet: 116355d4-c925-4c66-b49e-6ef8f64764cc
      security_groups:
      - bosh

resource_pools:
- name: services-small-z1
  cloud_properties:
    instance_type: m3.medium
```
