### ISSUE TITLE
Allow multiple RabbitMQ clusters per CF

### ISSUE THREAD

**Issue by rickfarmer** [pivotal-cf/cf-rabbitmq-release#9]
It appears that we currently allow only one RabbitMQ cluster per CF foundation because the service-uuid is set as a constant.  Please see https://github.com/pivotal-cf/cf-rabbitmq-release/blob/48ac8b7b3828aa74a514487a6fec396476a59a5d/src/rabbitmq-broker/src/clojure/io/pivotal/pcf/rabbitmq/config.clj#L15

The client is using this release for both PCF and CF (OSS) foundations (vSphere and AWS, respectively)  and view this as a potential capacity constraint since this will limit them to one rabbit cluster per CF.

I apologize if this is already in the Tracker, but I do not currently have access to it.  Please add me, if possible, so I can review our User Stories prior to submitting and to track stories as needed.

Thanks!

**Comment by benlaplanche** [comment]
Hi Rick,

To confirm the scenario in which you are experiencing the issue.
It sounds like you want to deploy this cf-rabbitmq-release multiple times against a single CF, to achieve having multiple RabbitMQ clusters?

Is that correct?
Thanks
Ben

**Comment by rickfarmer** [comment]
Thanks for the response, Ben.  Yes, that is exactly the scenario the client would like to achieve.

**Comment by michaelklishin** [comment]
Does https://github.com/pivotal-cf/cf-rabbitmq-release/pull/10 resolve this? or only partially address?

**Comment by davidehringer** [comment]
This is something we are very interested in as well (as PCF users).

**Comment by davidehringer** [comment]
Let me clarify our interest here as we don't necessarily need this specific solution but have a need that this could address.  What we are really looking for is to be able to provide some form of dedicated service instances that can be used by apps that need to have a guarantee that won't be affected by a noisy neighbor.  This is one way that could be done.  Having a dedicated plan option would be another.

**Comment by avade** [comment]
Thanks for the context David, I am the product manager for the PCF RabbitMQ tile at Pivotal.

The BOSH release now supports multiple cf-rabbitmq deployments running in the same CF / BOSH environment. This is not recommended or supported but has helped out some of the OSS users. This is not supported in PCF.

We are currently investigating how best to support 'dedicated' cluster instances provisioned via the same broker in a PCF environment.

**Comment by svett** [comment]
@davidehringer: 

We exposed the following properties:

```
rabbitmq-broker.service.name:
    description: "Name of the service"
    default: "p-rabbitmq"
  rabbitmq-broker.service.display_name:
    description: "Service offering display name in Apps Manager"
    default: "RabbitMQ"
  rabbitmq-broker.service.offering_description:
    description: "Service offering long description"
    default: "RabbitMQ is a robust and scalable high-performance multi-protocol messaging broker."
  rabbitmq-broker.service.uuid:
    description: "UUID of the service"
    default: "163b47c6-a2f3-43b1-97f7-b83b37ec8ad3"
  rabbitmq-broker.service.plan_uuid:
    description: "UUID of the plan"
    default: "4e816145-4e71-4e24-a402-0c686b868e2d"
```

That allows deploying multiple RabbitMQ clusters. I am closing this issue.
